### ISSUE TITLE
Is there any method to make infilling faster?

### ISSUE THREAD

**Issue by fuzhaiping** [NagabhushanSN95/DeCOMPnet#1]
Hello.In testing, infilling which cost 1s.
Is there any method to make infilling faster?

**Comment by NagabhushanSN95** [comment]
In our experiments, the deep learning operations for infilling took only about 4ms. It is the warping that is taking too much time. There exist faster implementations of warping (C++ or cuda itself). If you can merge our code with such warping solutions, infilling should become way faster.

**Comment by NagabhushanSN95** [comment]
Closing the issue. Reopen if there are any further queries.

**Comment by fuzhaiping** [comment]
Thank you very much for the reply.
By the way, is the world coordinate system of transformation (x,-y,-z)?
I would like to use my own camera extrinsics, but I don't know the correct world coordinate system.

**Comment by NagabhushanSN95** [comment]
Yes. It's correct. We use open CV coordinate system

**Comment by fuzhaiping** [comment]
Thank you!
