### ISSUE TITLE
Module Import Error when running ARFlowWeightsConverter01.py

### ISSUE THREAD

**Issue by jimmyfyx** [NagabhushanSN95/DeCOMPnet#7]
This is probably a bug. When running `ARFlowWeightsConverter01.py` , the imports seem to be valid only in the `src` folder, but  `ARFlowWeightsConverter01.py` is in `src/flow_estimation/utils`

**Comment by NagabhushanSN95** [comment]
Try `export PYTHONPATH=<ABSOLUTE_PATH_TO_SRC_DIR>:$PYTHONPATH`. That should work.

**Comment by NagabhushanSN95** [comment]
Closing this issue. Please reopen it if required.
