### ISSUE TITLE
Error when running test with pretrained weights

### ISSUE THREAD

**Issue by jimmyfyx** [NagabhushanSN95/DeCOMPnet#9]
Hi,

I'm trying to run the test with my own dataset which has image resolution as (640, 360). There are two modifications I make. First, I modify the config to include `train_configs['data_loader']['resolution_suffix'] = ['_down3']`. Then, I change the corresponding paths to read RGB and depth information for the data loader. I read the depth as `.png` instead of `.exr`. However, I get the following error message:

> The size of tensor a (12) must match the size of tensor b (11) at non-singleton dimension 2
Traceback (most recent call last):
  File "TerrasentiaTester01.py", line 112, in <module>
    main()
  File "TerrasentiaTester01.py", line 104, in main
    demo1()
  File "TerrasentiaTester01.py", line 100, in demo1
    start_testing(train_configs, test_configs)
  File "TerrasentiaTester01.py", line 20, in start_testing
    output_dirpath = Tester.start_testing(train_configs, test_configs, save_intermediate_results=False)                                                                                        
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 283, in start_testing
    pred_frames, masks, extras = tester.predict_next_frame2(video_name, seq_num, pred_frame_num,                                                                                               
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 101, in predict_next_frame2
    pred_frames, pred_frames_mask, extras = self.predict_next_frame1(input_dict, return_intermediate_results)                                                                                  
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 84, in predict_next_frame1
    output_batch = self.frame_predictor(input_batch, return_intermediate_results)
  File "/home/yixiaof2/.conda/envs/decomp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl                                                                     
    result = self.forward(*input, **kwargs)
  File "/home/yixiaof2/DeCOMPnet/src/frame_predictors/FramePredictor01.py", line 76, in forward
    flow_outputs = self.estimate_past_local_flow(flow_inputs)
  File "/home/yixiaof2/DeCOMPnet/src/frame_predictors/FramePredictor01.py", line 150, in estimate_past_local_flow                                                                              
    feature_extractor_output = self.feature_extractor(feature_extractor_input)
  File "/home/yixiaof2/.conda/envs/decomp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl                                                                     
    result = self.forward(*input, **kwargs)
  File "/home/yixiaof2/DeCOMPnet/src/flow_estimation/feature_extractors/PyramidFeatureExtractor01.py", line 55, in forward                                                                     
    x5a, m5a = self.conv5a(x4b, m4b)  # 8x8, 128
  File "/home/yixiaof2/.conda/envs/decomp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl                                                                     
    result = self.forward(*input, **kwargs)
  File "/home/yixiaof2/DeCOMPnet/src/flow_estimation/libraries/partial_convolution/partialconv3d.py", line 73, in forward                                                                      
    output = torch.mul(raw_out - bias_view, self.mask_ratio) + bias_view
RuntimeError: The size of tensor a (12) must match the size of tensor b (11) at non-singleton dimension 2                                                                                      
Program ended at 14/11/2023 05:05:29 PM
Execution time: 0:00:06.239132

Do you know what might be the reason for this? Thank you so much for the help.

**Comment by NagabhushanSN95** [comment]
The flow estimator has six downsampling operations. With your resolution, you can't downsample and upsample six times - you will hit an odd number somewhere. To verify if that is the issue, load patches of size `256x256` or `512x256`. If that works, then the issue with the odd resolution. You can either use patches or handle the odd resolution as suggested in the answers for [this question](https://stackoverflow.com/questions/66028743/how-to-handle-odd-resolutions-in-unet-architecture-pytorch).

**Comment by jimmyfyx** [comment]
Thank you! But I I believe the image resolution for VeedDynamic is 1920 * 1080 right? It seems that downsample and upsample six times is also not possible?

**Comment by NagabhushanSN95** [comment]
Right. That's where we first encountered an issue. We solved that issue by padding zeros along the height. Should be somewhere in the code. Observe that our data_loader has padding parameter, which does that.

**Comment by NagabhushanSN95** [comment]
However, your error looks somewhat different. We got the error in the skip connection. The downsampled and upsampled tensor had a different resolution than the one that didn't go through up/downsampling. Yours is coming in the partial convolution layer. It could be a bug in the partial convolution code as well. I remember we found one such bug in the original partial convolution code and fixed it. This could be another. If you can run it in debug mode and go step-by-step, you should be able to figure it out. In case you find it, either you can let us know or create a pull request. We will be glad to incorporate it.

**Comment by NagabhushanSN95** [comment]
> Right. That's where we first encountered an issue. We solved that issue by padding zeros along the height. Should be somewhere in the code. Observe that our data_loader has padding parameter, which does that.

My bad. Upsampling in the flow estimation is done to the specified resolution instead of upsampling by 2. So, odd resolution error shouldn't occur there. It can occur during [VideoInpainting](https://github.com/NagabhushanSN95/DeCOMPnet/blob/main/src/video_inpainting/flow_predictors/Unet01.py#L26--L58). There, we are downsampling only three times. So, both `1080` and `360` should be good. It shouldn't cause an issue during inpainting.

**Comment by jimmyfyx** [comment]
Thanks! So you mean the error I encountered is not the issue of odd resolution?

**Comment by NagabhushanSN95** [comment]
Not sure. One easy way to figure it out is to crop your input frames to `256x256` and see if it reproduces the error.

**Comment by jimmyfyx** [comment]
I see. Just want to make sure when running the test, is it necessary to add `resolution_suffix` to `train_config` for images other than `1920*1080`? Since in `src/data_loaders/VeedDynamic01.py` I see the `get_frame_resolution()` function but not seeing `self.frame_resolution` used anywhere. 

If it is necessary to specify a resolution suffix, how to deal with resolution that is not divisible by the original one. For instance, if I get the height of the image as 256. According to the code, it is scaled down by 4 from 1080, then the resulting height is rounded to 270, which is an odd number.

**Comment by NagabhushanSN95** [comment]
Hey, there is no necessity to specify resolution suffix if you don't have downsampled videos. Or you can pass an empty string.
